#!/usr/bin/env node
/**
 * fetch-data.mjs — Server-side data fetcher for GitHub Actions.
 *
 * Runs every 15 minutes via .github/workflows/fetch-data.yml.
 * Reads from Home Assistant (HA) and writes dashboard/public/data.json.
 * Secrets stay server-side — never exposed in the browser bundle.
 *
 * Usage:
 *   HA_BASE=https://ha.yourhost.nl HA_TOKEN=xxx node scripts/fetch-data.mjs
 */

import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dir = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(__dir, '../dashboard/public/data.json');

const HA_BASE = process.env.HA_BASE || process.env.VITE_HA_BASE || 'https://ha.richardheesen.nl';
const HA_TOKEN = process.env.HA_TOKEN || process.env.VITE_HA_TOKEN;
const ENTSOE_TOKEN = process.env.ENTSOE_TOKEN || process.env.VITE_ENTSOE_TOKEN;

// ── Entity IDs (Hendrik's Enphase Envoy) ─────────────────────────────────────
const ENTITIES = {
  productionW:         'sensor.envoy_122503008953_current_power_production',
  consumptionW:        'sensor.envoy_122503008953_current_power_consumption',
  netW:                'sensor.envoy_122503008953_current_net_power_consumption',
  productionTodayWh:   'sensor.envoy_122503008953_today_s_energy_production',
  consumptionTodayWh:  'sensor.envoy_122503008953_today_s_energy_consumption',
  batteryPct:          'sensor.envoy_122503008953_total_battery_percentage',
  priceNow:            'sensor.energyzero_today_energy_current_hour_price',
  priceAvg:            'sensor.energyzero_today_energy_average_price',
};

async function fetchHaState(entityId) {
  const url = `${HA_BASE}/api/states/${encodeURIComponent(entityId)}`;
  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${HA_TOKEN}`,
      'Content-Type': 'application/json',
    },
    signal: AbortSignal.timeout(10_000),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`HA ${res.status} ${entityId}: ${body.slice(0, 100)}`);
  }
  return res.json();
}

function num(state) {
  const n = Number(state?.state);
  return isNaN(n) ? 0 : n;
}

function whToKwh(wh) {
  return wh / 1000;
}

async function main() {
  if (!HA_TOKEN) {
    console.error('[fetch-data] HA_TOKEN not set. Set HA_TOKEN in environment.');
    process.exit(1);
  }

  console.log('[fetch-data] Fetching Home Assistant states…');

  let energy = { productionW: 0, consumptionW: 0, netW: 0, productionTodayKwh: 0, consumptionTodayKwh: 0, batteryPct: 0 };
  let revenue = { currentPriceEurKwh: 0, revenuePerHourEur: 0, todayEstimateEur: 0 };

  try {
    const results = await Promise.all(
      Object.entries(ENTITIES).map(async ([key, id]) => [key, await fetchHaState(id)]),
    );
    const map = Object.fromEntries(results);

    const productionW        = num(map.productionW);
    const consumptionW       = num(map.consumptionW);
    const netW               = num(map.netW);
    const productionTodayKwh = whToKwh(num(map.productionTodayWh));
    const consumptionTodayKwh= whToKwh(num(map.consumptionTodayWh));
    const batteryPct         = num(map.batteryPct);
    const priceNow           = num(map.priceNow);   // €/kWh
    const priceAvg           = num(map.priceAvg);   // €/kWh

    energy = { productionW, consumptionW, netW, productionTodayKwh, consumptionTodayKwh, batteryPct };

    // Revenue math (mirrors src/lib/revenue.js)
    // netW < 0 means exporting to grid → earning money
    const exportW = Math.max(-netW, 0);
    const importW = Math.max(netW, 0);
    const revenuePerHourEur = (exportW / 1000) * priceNow - (importW / 1000) * priceNow;
    const netExportKwh = productionTodayKwh - consumptionTodayKwh;
    const todayEstimateEur = netExportKwh * priceAvg;

    revenue = { currentPriceEurKwh: priceNow, revenuePerHourEur, todayEstimateEur };

    console.log(`[fetch-data] ✅ productie=${productionW}W verbruik=${consumptionW}W prijs=${priceNow}€/kWh`);
  } catch (err) {
    console.error(`[fetch-data] HA fetch failed: ${err.message}`);
    // Don't exit — write placeholder so the site still loads.
  }

  const output = {
    _note: 'Auto-generated by GitHub Actions every 15 minutes. Do not edit.',
    _updatedAt: new Date().toISOString(),
    energy,
    revenue,
    prices: [], // Reserved for future ENTSO-E price array
  };

  writeFileSync(OUTPUT, JSON.stringify(output, null, 2) + '\n');
  console.log(`[fetch-data] Written to ${OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
